### ISSUE TITLE
E11000 duplicate key error collection: mongolog.mongolog

### ISSUE THREAD

**Issue by agusmakmun** [gnulnx/django-mongolog#81]
How I can handle duplicate key error, when I following this `django-mongolog`?

![image](https://user-images.githubusercontent.com/7134451/61357750-119abd00-a8a3-11e9-8ff5-092312162878.png)

```
{
  code: 11000, 
  errmsg: 'E11000 duplicate key error collection: mongolog.mongolog index: uuid_1 dup key: { : "e5a55c46a3b759839df3d1ea99ea813f" }', 
  index: 0
}
```

**Comment by gnulnx** [comment]
I would need to see your code to understand this better, but the duplicate key error is likely arising from something on your end.  

Sorry about the super late reply here.  If this is still an issue reopen with example code to reproduce and I'll take a look.
